---
- name: Install common yum packages
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - git
    - tree
    - tmux

- name: Fix crontab/vi issue on Amazon Linux
  file:
    src: /usr/bin/vim
    dest: /usr/bin/vi
    state: link
    owner: root
    group: root

- name: Copy the tmux config
  template:
    src: tmux.conf.j2
    dest: /home/ec2-user/.tmux.conf
    owner: ec2-user
    group: ec2-user
    mode: 0644
